### ISSUE TITLE
When `CannotFindBinaryPath`, display name of binary that cannot be found

### ISSUE THREAD

**Issue by abernix** [apollographql/federation-rs#121] opened 2022-05-19 08:33 UTC
Currently, if you try building this without `npm` installed, you'll receive a message like this:

```
`Result::unwrap()` on an `Err` value: CannotFindBinaryPath', /usr/local/cargo/git/checkouts/federation-rs-edb4f8c0f5624a5c/33659ef/federation-2/router-bridge/build.rs:23:35
```

Nowhere in the message does it say what binary cannot be found.  Can we improve that message to help self-diagnosis and resolution?

### Reproduction steps

You can probably just get `npm` out of your path and reproduce this — idk, `mv npm npm.bu` — but Docker is also a reasonable place to try this!

**Comment by SimonSapin** [comment] 2022-05-20 12:58
This was fixed in 8fe2c49e. The error now looks like this:

```
error: failed to run custom build command for `router-bridge v0.1.0 (/Users/simon/projects/federation-rs/federation-2/router-bridge)`

Caused by:
  process didn't exit successfully: `/Users/simon/projects/federation-rs/federation-2/target/debug/build/router-bridge-6e3cb1ccec9f4c87/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=js-src
  cargo:warning=Updating router-bridge

  --- stderr
  thread 'main' panicked at ''npm' is not available: CannotFindBinaryPath', router-bridge/build.rs:23:35
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Closed by SimonSapin** 2022-05-20 12:58 UTC
